<template>
  <category :categories='categories'></category>
</template>
<script>
  import category from './common/category';
  export default{
    data(){
      return {
        categories:{
          title:'周边',
          category:[
            {title:'热门', type:'hot'},
            {title:'服装', type:'clothes'},
            {title:'米兔', type:'mitu'},
            {title:'生活周边', type:'around'},
            {title:'箱包', type:'box'}
          ],
          left:[
            {sourceUrl:'http://list.mi.com/22',imgUrl:'http://i3.mifile.cn/a4/377adfa2-9a40-4b66-a8ed-5ae862a2dfa8'},
            {sourceUrl:'http://list.mi.com/accessories/tag?id=rujiaozhen', imgUrl:'http://i3.mifile.cn/a4/37dc80cf-baf4-427a-aee9-7b0f8b7fac3d'}
          ],
          hot:[
            {
              sourceUrl:'http://item.mi.com/1163300013.html',
              imgUrl:'http://i3.mifile.cn/a4/c4f91846-3927-4778-9bb0-a865dedeb85e',
              title:'圆领套头卫衣',
              price:99,
              commentNum:'328',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼',
              isSpecial:true,
              specialText:'新品',
              specialColor:'#83c44e'
            },
            {
              sourceUrl:'http://item.mi.com/1163200001.html',
              imgUrl:'http://i3.mifile.cn/a4/3d2ad1e5-6e04-45ae-aecb-c745a67f0d0f',
              title:'小米摇粒绒加厚保暖外套 男款',
              price:99,
              commentNum:'413',
              newestComment:'手感超舒服，有USB C输入充电，以后不用到处换插头了',
              newestFrom:'LIN翼',
              isSpecial:true,
              specialText:'新品',
              specialColor:'#83c44e'
            },
            {
              sourceUrl:'http://item.mi.com/1163200006.html',
              imgUrl:'http://i3.mifile.cn/a4/e66a939b-2645-4ddb-bfe9-c2543029e8bd',
              title:'小米空气层连帽运动卫衣 男款',
              price:199,
              commentNum:'72',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼',
              isSpecial:true,
              specialText:'新品',
              specialColor:'#83c44e'
            },
            {
              sourceUrl:'http://item.mi.com/1163300034.html',
              imgUrl:'http://i3.mifile.cn/a4/d0fef67b-8f3c-4b5a-af8d-0f588b946f6a',
              title:'经典连帽休闲卫衣',
              price:149,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼',
              isSpecial:true,
              specialText:'新品',
              specialColor:'#83c44e'
            },
            {
              sourceUrl:'http://item.mi.com/1161100002.html',
              imgUrl:'http://i3.mifile.cn/a4/6ddc1df6-ce8e-4cb5-a26a-b5ef80f1adf7',
              title:'小米经典商务双肩包',
              price:99,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼',
              isSpecial:true,
              specialText:'新品',
              specialColor:'#83c44e'
            },
            {
              sourceUrl:'http://www.mi.com/mimosdge/',
              imgUrl:'http://i1.mifile.cn/a1/pms_1468310472.00391359!220x220.jpg',
              title:'米家随身电蚊香',
              price:29,
              commentNum:'2863',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1162800009.html',
              imgUrl:'http://i3.mifile.cn/a4/5a28d943-ef5d-4920-a89a-7f1bce6c5b35',
              title:'米家LED随身灯 增强版',
              price:19.9,
              commentNum:'5277',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼',
              isSpecial:true,
              specialText:'新品',
              specialColor:'#83c44e'
            },
            {
              sourceUrl1:'http://item.mi.com/1144600004.html',
              imgUrl:'http://i3.mifile.cn/a4/T1yo_gBm_v1RXrhCrK.jpg',
              title:'金属鼠标垫 小',
              price:49,
              sourceUrl2:'http://list.mi.com/zhoubian'
            }
          ],
          clothes:[
            {
              sourceUrl:'http://item.mi.com/1151900011.html',
              imgUrl:'http://i2.mifile.cn/a1/T12HJvByEv1RXrhCrK.jpg?width=150&height=150',
              title:'小米移动电源',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1160900029.html',
              imgUrl:'http://i2.mifile.cn/a1/T1eSZgBjVT1RXrhCrK.jpg?width=150&height=150',
              title:'小米移动电源10000mAh 高配版',
              price:79,
              commentNum:'19.7万',
              newestComment:'手感超舒服，有USB C输入充电，以后不用到处换插头了',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1161200010.html',
              imgUrl:'http://i2.mifile.cn/a1/T1ycK_BjYv1RXrhCrK.jpg?width=150&height=150',
              title:'小米圈铁耳机',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1151400001.html',
              imgUrl:'http://i2.mifile.cn/a1/pms_1463579883.27084326.jpg?width=150&height=150',
              title:'小米插线板',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1154300036.html',
              imgUrl:'http://i2.mifile.cn/a1/T1F5K_BjVv1RXrhCrK.jpg?width=150&height=150',
              title:'小米小钢炮蓝牙音箱2',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1154400043.html',
              imgUrl:'http://i2.mifile.cn/a1/T1vFEjBbWT1RXrhCrK.jpg?width=150&height=150',
              title:'小米USB充电器（4口）',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1151900011.html',
              imgUrl:'http://i2.mifile.cn/a1/T12HJvByEv1RXrhCrK.jpg?width=150&height=150',
              title:'小米移动电源',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl1:'http://item.mi.com/1154500022.html',
              imgUrl:'http://i3.mifile.cn/a4/T1Ihd_BTCv1RXrhCrK.jpg',
              title:'小米小钢炮',
              price:39,
              sourceUrl2:'http://list.mi.com/dapei'
            }
          ],
          mitu:[
            {
              sourceUrl:'http://www.mi.com/dianyuan5000/',
              imgUrl:'http://i3.mifile.cn/a4/T1AcE_Bghv1RXrhCrK.jpg',
              title:'移动电源5000mAh',
              price:7999,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://www.mi.com/dianyuan10000/',
              imgUrl:'http://i1.mifile.cn/a1/T12HJvByEv1RXrhCrK!220x220.jpg',
              title:'移动电源10000mAh',
              price:79,
              commentNum:'19.7万',
              newestComment:'手感超舒服，有USB C输入充电，以后不用到处换插头了',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://www.mi.com/dianyuan10000/pro/',
              imgUrl:'http://i1.mifile.cn/a1/T1eSZgBjVT1RXrhCrK!220x220.jpg',
              title:'移动电源10000mAh 高配版',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1154400042.html',
              imgUrl:'http://i3.mifile.cn/a4/T1x8J_BgEv1RXrhCrK.jpg',
              title:'移动电源20000mAh',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1152000009.html',
              imgUrl:'http://i1.mifile.cn/a1/T1vSDQB4_T1RXrhCrK!220x220.jpg',
              title:'10000mAh小米移动电源保护套',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://www.mi.com/powerstrip/',
              imgUrl:'http://i3.mifile.cn/a4/T1jMbjB5Jv1RXrhCrK.jpg',
              title:'小米插线板（3孔位+USB）',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://www.mi.com/chongdianqi4kou/',
              imgUrl:'http://i1.mifile.cn/a1/T1vFEjBbWT1RXrhCrK!220x220.jpg',
              title:'小米USB充电器（4口）',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl1:'http://item.mi.com/1154500022.html',
              imgUrl:'http://i3.mifile.cn/a4/T1Ihd_BTCv1RXrhCrK.jpg',
              title:'小米小钢炮',
              price:39,
              sourceUrl2:'http://list.mi.com/dapei'
            }
          ],
          around:[
            {
              sourceUrl:'http://item.mi.com/1134900527.html',
              imgUrl:'http://i1.mifile.cn/a1/T1sRhTBsYT1RXrhCrK!220x220.jpg',
              title:'SanDisk 16GB存储卡（Class4）',
              price:79999,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1153300072.html',
              imgUrl:'http://i1.mifile.cn/a1/T1ipAvB_ZT1RXrhCrK!220x220.jpg',
              title:'原装快充套装',
              price:79,
              commentNum:'19.7万',
              newestComment:'手感超舒服，有USB C输入充电，以后不用到处换插头了',
              newestFrom:'LIN翼',
              isSpecial:true,
              specialText:'享8折',
              specialColor:'#e53935'
            },
            {
              sourceUrl:'http://item.mi.com/1154300033.html',
              imgUrl:'http://i1.mifile.cn/a1/T1xxVTBghv1RXrhCrK!220x220.jpg',
              title:'彩虹5号电池（10粒装）',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1155000010.html',
              imgUrl:'http://i1.mifile.cn/a1/T178EjBjVT1RXrhCrK!220x220.jpg',
              title:'彩虹7号电池（10粒装）',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1154600004.html',
              imgUrl:'http://i3.mifile.cn/a4/T1PGb_BKAv1RXrhCrK.jpg',
              title:'米兔手机U盘升级版 32GB',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://www.mi.com/recharger/',
              imgUrl:'http://i3.mifile.cn/a4/T1gVCgBjDv1RXrhCrK.jpg',
              title:'紫5镍氢充电电池',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1154400043.html',
              imgUrl:'http://i1.mifile.cn/a1/T142A_BXEv1RXrhCrK!220x220.jpg',
              title:'小米车载充电器',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl1:'http://item.mi.com/1152400014.html',
              imgUrl:'http://i1.mifile.cn/a1/T1_lKvBKZT1RXrhCrK!220x220.jpg',
              title:'红米2/红米2A',
              price:39,
              sourceUrl2:'http://list.mi.com/135'
            }
          ],
          box:[
            {
              sourceUrl:'http://www.mi.com/dianyuan5000/',
              imgUrl:'http://i3.mifile.cn/a4/T1AcE_Bghv1RXrhCrK.jpg',
              title:'移动电源5000mAh',
              price:7999,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://www.mi.com/dianyuan10000/',
              imgUrl:'http://i1.mifile.cn/a1/T12HJvByEv1RXrhCrK!220x220.jpg',
              title:'移动电源10000mAh',
              price:79,
              commentNum:'19.7万',
              newestComment:'手感超舒服，有USB C输入充电，以后不用到处换插头了',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://www.mi.com/dianyuan10000/pro/',
              imgUrl:'http://i1.mifile.cn/a1/T1eSZgBjVT1RXrhCrK!220x220.jpg',
              title:'移动电源10000mAh 高配版',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1154400042.html',
              imgUrl:'http://i3.mifile.cn/a4/T1x8J_BgEv1RXrhCrK.jpg',
              title:'移动电源20000mAh',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1152000009.html',
              imgUrl:'http://i1.mifile.cn/a1/T1vSDQB4_T1RXrhCrK!220x220.jpg',
              title:'10000mAh小米移动电源保护套',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://www.mi.com/powerstrip/',
              imgUrl:'http://i3.mifile.cn/a4/T1jMbjB5Jv1RXrhCrK.jpg',
              title:'小米插线板（3孔位+USB）',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://www.mi.com/chongdianqi4kou/',
              imgUrl:'http://i1.mifile.cn/a1/T1vFEjBbWT1RXrhCrK!220x220.jpg',
              title:'小米USB充电器（4口）',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl1:'http://item.mi.com/1154500022.html',
              imgUrl:'http://i3.mifile.cn/a4/T1Ihd_BTCv1RXrhCrK.jpg',
              title:'小米小钢炮',
              price:39,
              sourceUrl2:'http://list.mi.com/dapei'
            }
          ]
        }
      }
    },
    components:{
      category
    }
  }
</script>
<style lang="scss"></style>
