<template>
  <div class="content-container">
    <div class="content-title">
      <h2 class="goods-title">內容</h2>
    </div>
    <div class="content-slide clearfix">
        <small-slide v-for="datas in allDatas"></small-slide>
    </div>
  </div>
</template>
<script>
  import smallSlide from './common/smallSlide';
  export default{
    data(){
      return {
        allDatas:[
        	{
        		name:'图书',
        		color:'#ffac13',
        		slides:[
        				{
        					sourceUrl:'http://www.duokan.com/book/115222',
        					imgUrl:'http://i3.mifile.cn/a4/8e3584b6-3169-41c6-9356-939ec79aac2b',
        					title:'哈利·波特与魔法石',
        					intro:'哈利波特来了!',
        					hasTitle:true,
        					isFree:false,
        					hasBtn:false
        				},
        				{
        					sourceUrl:'http://www.duokan.com/special/7812',
        					imgUrl:'http://i3.mifile.cn/a4/T1dlVgBbbT1RXrhCrK.jpg',
        					title:'特价专区',
        					intro:'精选畅销好书，特价促销，天天更新，天天特价！',
        					hasTitle:true,
        					isFree:true,
        					freeText:'限时优惠',
        					hasBtn:false
        				},
        				{
        					sourceUrl:'http://www.duokan.com/list/9-1',
        					imgUrl:'http://i3.mifile.cn/a4/T1R3WgBjKT1RXrhCrK.jpg',
        					title:'杂志专区',
        					intro:'纸媒杂志＋互联网杂志，你想看的这都有！',
        					hasTitle:true,
        					isFree:true,
        					freeText:'同步新刊上线',
        					hasBtn:false
        				},
        				{
        					sourceUrl:'http://www.duokan.com/book/115222',
        					imgUrl:'http://i3.mifile.cn/a4/8e3584b6-3169-41c6-9356-939ec79aac2b',
        					intro:'哈利波特来了!',
        					hasTitle:false,
        					isFree:false,
        					hasBtn:true,
        					btnText:'前往多看阅读',
        					btnUrl:'http://www.duokan.com/list/1-1?from=xiaomi'
        				}
        			]
        	},
        	{
        		name:'MIUI 主题',
        		color:'#83c44e',
        		slides:[
        				{
        					sourceUrl:'http://zhuti.xiaomi.com/detail/e634e003-bbfc-4782-92e0-c8759bb99256',
        					imgUrl:'http://i3.mifile.cn/a4/f824eaec-20c3-4163-aa82-b0b3b324714b',
        					title:'剑侠世界',
        					intro:'游戏同名主题，免费下载！吴亦凡陪你仗剑江湖！',
        					hasTitle:true,
        					isFree:true,
        					freeText:'免费',
        					hasBtn:false
        				},
        				{
        					sourceUrl:'http://www.duokan.com/special/7812',
        					imgUrl:'http://i3.mifile.cn/a4/T1dlVgBbbT1RXrhCrK.jpg',
        					title:'特价专区',
        					intro:'精选畅销好书，特价促销，天天更新，天天特价！',
        					hasTitle:true,
        					isFree:true,
        					freeText:'限时优惠',
        					hasBtn:false
        				},
        				{
        					sourceUrl:'http://www.duokan.com/list/9-1',
        					imgUrl:'http://i3.mifile.cn/a4/T1R3WgBjKT1RXrhCrK.jpg',
        					title:'杂志专区',
        					intro:'纸媒杂志＋互联网杂志，你想看的这都有！',
        					hasTitle:true,
        					isFree:true,
        					freeText:'同步新刊上线',
        					hasBtn:false
        				},
        				{
        					sourceUrl:'http://www.duokan.com/book/115222',
        					imgUrl:'http://i3.mifile.cn/a4/8e3584b6-3169-41c6-9356-939ec79aac2b',
        					intro:'哈利波特来了!',
        					hasTitle:false,
        					isFree:false,
        					hasBtn:true,
        					btnText:'前往多看阅读',
        					btnUrl:'http://www.duokan.com/list/1-1?from=xiaomi'
        				}
        			]
        	},
        	{
        		name:'游戏',
        		color:'#e53935',
        		slides:[
        				{
        					sourceUrl:'http://jxsjgw.mi.com/',
        					imgUrl:'http://i3.mifile.cn/a4/695c909b-f541-4575-bace-d08b6465025b',
        					title:'剑侠世界',
        					intro:'一生不容错过的浪漫武侠！！',
        					hasTitle:true,
        					isFree:true,
        					freeText:'免费',
        					hasBtn:false
        				},
        				{
        					sourceUrl:'http://www.duokan.com/special/7812',
        					imgUrl:'http://i3.mifile.cn/a4/T1dlVgBbbT1RXrhCrK.jpg',
        					title:'特价专区',
        					intro:'精选畅销好书，特价促销，天天更新，天天特价！',
        					hasTitle:true,
        					isFree:true,
        					freeText:'限时优惠',
        					hasBtn:false
        				},
        				{
        					sourceUrl:'http://www.duokan.com/list/9-1',
        					imgUrl:'http://i3.mifile.cn/a4/T1R3WgBjKT1RXrhCrK.jpg',
        					title:'杂志专区',
        					intro:'纸媒杂志＋互联网杂志，你想看的这都有！',
        					hasTitle:true,
        					isFree:true,
        					freeText:'同步新刊上线',
        					hasBtn:false
        				},
        				{
        					sourceUrl:'http://www.duokan.com/book/115222',
        					imgUrl:'http://i3.mifile.cn/a4/8e3584b6-3169-41c6-9356-939ec79aac2b',
        					intro:'哈利波特来了!',
        					hasTitle:false,
        					isFree:false,
        					hasBtn:true,
        					btnText:'前往多看阅读',
        					btnUrl:'http://www.duokan.com/list/1-1?from=xiaomi'
        				}
        			]
        	},
        	{
        		name:'应用',
        		color:'#2196f3',
        		slides:[
        				{
        					sourceUrl:'http://app.mi.com/subject/168797',
        					imgUrl:'http://i3.mifile.cn/a4/T1YyJgBCYv1R4cSCrK.png',
        					title:'2015年度应用',
        					intro:'2015年度应用!',
        					hasTitle:true,
        					isFree:true,
        					freeText:'免费',
        					hasBtn:false
        				},
        				{
        					sourceUrl:'http://www.duokan.com/special/7812',
        					imgUrl:'http://i3.mifile.cn/a4/T1dlVgBbbT1RXrhCrK.jpg',
        					title:'特价专区',
        					intro:'精选畅销好书，特价促销，天天更新，天天特价！',
        					hasTitle:true,
        					isFree:true,
        					freeText:'限时优惠',
        					hasBtn:false
        				},
        				{
        					sourceUrl:'http://www.duokan.com/list/9-1',
        					imgUrl:'http://i3.mifile.cn/a4/T1R3WgBjKT1RXrhCrK.jpg',
        					title:'杂志专区',
        					intro:'纸媒杂志＋互联网杂志，你想看的这都有！',
        					hasTitle:true,
        					isFree:true,
        					freeText:'同步新刊上线',
        					hasBtn:false
        				},
        				{
        					sourceUrl:'http://www.duokan.com/book/115222',
        					imgUrl:'http://i3.mifile.cn/a4/8e3584b6-3169-41c6-9356-939ec79aac2b',
        					intro:'哈利波特来了!',
        					hasTitle:false,
        					isFree:false,
        					hasBtn:true,
        					btnText:'前往多看阅读',
        					btnUrl:'http://www.duokan.com/list/1-1?from=xiaomi'
        				}
        			]
        	}
        ]
      };
    },
    components:{
      'small-slide':smallSlide
    }
  }
</script>
<style lang="scss">
  .content-container{
    width:1226px;
    height:478px;
    margin:10px auto;
    .content-title{
      width:1226px;
      height:58px;
      line-height:58px;
      overflow: hidden;
    }
    .content-slide{
      width:1226px;
      height:420px;
    }
    .small-container{
      margin:0px 0px 14px 14px;
      &:nth-of-type(1){
        margin-left:0;
      }
    }
  }
</style>
