<template>
  <category :categories='categories'></category>
</template>
<script>
  import category from './common/category';
  export default{
    data(){
      return {
        categories:{
          title:'搭配',
          category:[
            {title:'热门', type:'hot'},
            {title:'耳机音箱', type:'airPhone'},
            {title:'电源', type:'power'},
            {title:'电池存储卡', type:'card'}
          ],
          left:[
            {sourceUrl:'http://www.mi.com/dianyuan10000/',imgUrl:'http://i3.mifile.cn/a4/809aed51-f9b9-482e-a249-93d44225439e'},
            {sourceUrl:'http://www.mi.com/capsuleearphone/', imgUrl:'http://i3.mifile.cn/a4/ffe46b8a-6c97-4b92-a053-da243df50e23'}
          ],
          hot:[
            {
              sourceUrl:'http://item.mi.com/1151900011.html',
              imgUrl:'http://i2.mifile.cn/a1/T12HJvByEv1RXrhCrK.jpg?width=150&height=150',
              title:'小米移动电源',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1160900029.html',
              imgUrl:'http://i2.mifile.cn/a1/T1eSZgBjVT1RXrhCrK.jpg?width=150&height=150',
              title:'小米移动电源10000mAh 高配版',
              price:79,
              commentNum:'19.7万',
              newestComment:'手感超舒服，有USB C输入充电，以后不用到处换插头了',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1161200010.html',
              imgUrl:'http://i2.mifile.cn/a1/T1ycK_BjYv1RXrhCrK.jpg?width=150&height=150',
              title:'小米圈铁耳机',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1151400001.html',
              imgUrl:'http://i2.mifile.cn/a1/pms_1463579883.27084326.jpg?width=150&height=150',
              title:'小米插线板',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1154300036.html',
              imgUrl:'http://i2.mifile.cn/a1/T1F5K_BjVv1RXrhCrK.jpg?width=150&height=150',
              title:'小米小钢炮蓝牙音箱2',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1154400043.html',
              imgUrl:'http://i2.mifile.cn/a1/T1vFEjBbWT1RXrhCrK.jpg?width=150&height=150',
              title:'小米USB充电器（4口）',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1151900011.html',
              imgUrl:'http://i2.mifile.cn/a1/T12HJvByEv1RXrhCrK.jpg?width=150&height=150',
              title:'小米移动电源',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl1:'http://item.mi.com/1154500022.html',
              imgUrl:'http://i3.mifile.cn/a4/T1Ihd_BTCv1RXrhCrK.jpg',
              title:'小米小钢炮',
              price:39,
              sourceUrl2:'http://list.mi.com/dapei'
            }
          ],
          airPhone:[
            {
              sourceUrl:'http://www.mi.com/quantie/',
              imgUrl:'http://i1.mifile.cn/a1/pms_1467184989.74561304!220x220.jpg',
              title:'小米圈铁耳机 银色',
              price:799,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://www.mi.com/quantie/',
              imgUrl:'http://i1.mifile.cn/a1/T1ycK_BjYv1RXrhCrK!220x220.jpg',
              title:'小米圈铁耳机',
              price:79,
              commentNum:'19.7万',
              newestComment:'手感超舒服，有USB C输入充电，以后不用到处换插头了',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1161800009.html',
              imgUrl:'http://i1.mifile.cn/a1/T1SkV_BCd_1RXrhCrK!220x220.jpg',
              title:'小米胶囊耳机',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://www.mi.com/bluetooth-headset/',
              imgUrl:'http://i1.mifile.cn/a1/T190DvB4dv1RXrhCrK!220x220.jpg',
              title:'小米蓝牙耳机',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://www.mi.com/yinxiang/',
              imgUrl:'http://i1.mifile.cn/a1/T1Tfd_BjAv1RXrhCrK!220x220.jpg',
              title:'小米小钢炮蓝牙音箱2',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://www.mi.com/littleaudio/',
              imgUrl:'http://i1.mifile.cn/a1/T1LqYgBCWv1RXrhCrK!220x220.jpg',
              title:'小米USB充电器（4口）',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://www.mi.com/pocketaudio/',
              imgUrl:'http://i1.mifile.cn/a1/T1yf__BjAT1RXrhCrK!220x220.jpg',
              title:'小米蓝牙音箱',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl1:'http://www.mi.com/speaker/',
              imgUrl:'http://i1.mifile.cn/a1/T15hZ_BsDv1RXrhCrK!220x220.jpg',
              title:'小米小钢炮',
              price:39,
              sourceUrl2:'http://list.mi.com/17'
            }
          ],
          power:[
            {
              sourceUrl:'http://www.mi.com/dianyuan5000/',
              imgUrl:'http://i3.mifile.cn/a4/T1AcE_Bghv1RXrhCrK.jpg',
              title:'移动电源5000mAh',
              price:7999,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://www.mi.com/dianyuan10000/',
              imgUrl:'http://i1.mifile.cn/a1/T12HJvByEv1RXrhCrK!220x220.jpg',
              title:'移动电源10000mAh',
              price:79,
              commentNum:'19.7万',
              newestComment:'手感超舒服，有USB C输入充电，以后不用到处换插头了',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://www.mi.com/dianyuan10000/pro/',
              imgUrl:'http://i1.mifile.cn/a1/T1eSZgBjVT1RXrhCrK!220x220.jpg',
              title:'移动电源10000mAh 高配版',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1154400042.html',
              imgUrl:'http://i3.mifile.cn/a4/T1x8J_BgEv1RXrhCrK.jpg',
              title:'移动电源20000mAh',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1152000009.html',
              imgUrl:'http://i1.mifile.cn/a1/T1vSDQB4_T1RXrhCrK!220x220.jpg',
              title:'10000mAh小米移动电源保护套',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://www.mi.com/powerstrip/',
              imgUrl:'http://i3.mifile.cn/a4/T1jMbjB5Jv1RXrhCrK.jpg',
              title:'小米插线板（3孔位+USB）',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://www.mi.com/chongdianqi4kou/',
              imgUrl:'http://i1.mifile.cn/a1/T1vFEjBbWT1RXrhCrK!220x220.jpg',
              title:'小米USB充电器（4口）',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl1:'http://item.mi.com/1154500022.html',
              imgUrl:'http://i3.mifile.cn/a4/T1Ihd_BTCv1RXrhCrK.jpg',
              title:'小米小钢炮',
              price:39,
              sourceUrl2:'http://list.mi.com/dapei'
            }
          ],
          card:[
            {
              sourceUrl:'http://item.mi.com/1134900527.html',
              imgUrl:'http://i1.mifile.cn/a1/T1sRhTBsYT1RXrhCrK!220x220.jpg',
              title:'SanDisk 16GB存储卡（Class4）',
              price:79999,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1153300072.html',
              imgUrl:'http://i1.mifile.cn/a1/T1ipAvB_ZT1RXrhCrK!220x220.jpg',
              title:'原装快充套装',
              price:79,
              commentNum:'19.7万',
              newestComment:'手感超舒服，有USB C输入充电，以后不用到处换插头了',
              newestFrom:'LIN翼',
              isSpecial:true,
              specialText:'享8折',
              specialColor:'#e53935'
            },
            {
              sourceUrl:'http://item.mi.com/1154300033.html',
              imgUrl:'http://i1.mifile.cn/a1/T1xxVTBghv1RXrhCrK!220x220.jpg',
              title:'彩虹5号电池（10粒装）',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1155000010.html',
              imgUrl:'http://i1.mifile.cn/a1/T178EjBjVT1RXrhCrK!220x220.jpg',
              title:'彩虹7号电池（10粒装）',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1154600004.html',
              imgUrl:'http://i3.mifile.cn/a4/T1PGb_BKAv1RXrhCrK.jpg',
              title:'米兔手机U盘升级版 32GB',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://www.mi.com/recharger/',
              imgUrl:'http://i3.mifile.cn/a4/T1gVCgBjDv1RXrhCrK.jpg',
              title:'紫5镍氢充电电池',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl:'http://item.mi.com/1154400043.html',
              imgUrl:'http://i1.mifile.cn/a1/T142A_BXEv1RXrhCrK!220x220.jpg',
              title:'小米车载充电器',
              price:79,
              commentNum:'19.7万',
              newestComment:'这个小巧玲珑啊，比10400安的小了好多，感觉不错，...',
              newestFrom:'LIN翼'
            },
            {
              sourceUrl1:'http://item.mi.com/1152400014.html',
              imgUrl:'http://i1.mifile.cn/a1/T1_lKvBKZT1RXrhCrK!220x220.jpg',
              title:'红米2/红米2A',
              price:39,
              sourceUrl2:'http://list.mi.com/135'
            }
          ]
        }
      }
    },
    components:{
      category
    }
  }
</script>
<style lang="scss"></style>
